version: 2
updates:
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/calculator-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "calculator-team"
    assignees:
      - "calculator-team"
    commit-message:
      prefix: "feat"
      include: "scope"

  # Enable version updates for pip (backend)
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "calculator-team"
    assignees:
      - "calculator-team"
    commit-message:
      prefix: "feat"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"